#include <fstream>
#include <string_view>
#include <utility>
#include <bitset>

const char* comment = 
R"(/*
This is code that was auto generated by a Troy Hamilton script.
The std::size_t variables represent the hashes of strings as
binary integer literals.

As of C++ 23 on 10-15-2024, std::hash is not constexpr, meaning
it is not possible to implement a switch-case statement on
string hashes. This auto generated code is the crispiest solution.

Just be sure to recompile your program each time you need to update
your hashes, because currently "case:" labels must be constexpr'd.

Note: urls must not contain any whitespace.
*/

)";

std::string urls_src = "valid_urls.txt";
std::string hash_dst = "url_hashes.cpp";

int main()
{
    std::ifstream src(urls_src);
    std::ofstream outfile(hash_dst);

    outfile << comment;

    std::string var_name;
    std::string url_string;

    while(1)
    {
        src >> var_name >> url_string;

        if(src.eof())
            break;

        std::string url(url_string, 1, url_string.length() - 2);

        std::size_t hash = std::hash<std::string_view>()(url);
        std::bitset<sizeof(std::size_t) * 8> bitfield(hash);

        outfile 
        << "// \"" << url << "\"" << std::endl
        << "const std::size_t " << var_name 
        << " = {0b" << bitfield.to_string() << "};\n\n";
    }

    outfile.close();
}

