/*
This is code that was auto generated by a Troy Hamilton script.
The std::size_t variables represent the hashes of strings as
binary integer literals.

As of C++ 23 on 10-15-2024, std::hash is not constexpr, meaning
it is not possible to implement a switch-case statement on
string hashes. This auto generated code is the crispiest solution.

Just be sure to recompile your program each time you need to update
your hashes, because currently "case:" labels must be constexpr'd.

Note: urls must not contain any whitespace.
*/

// ""
const std::size_t empty_path = {0b0101010100111110100100111001000000011110010001100010101001101110};

// "index.html"
const std::size_t index = {0b1111010111110100111110000111101010110011011100010011110100001110};

// "very-complicated-and-long-url"
const std::size_t complicated = {0b0111010111000010100001001101101000000000101100111111011011110011};

